# Generated by Django 4.2.7 on 2024-02-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elearning_app", "0005_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=256, unique=True)),
                ("chat_log", models.TextField(blank=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning_app.appuser",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="members", to="elearning_app.appuser"
                    ),
                ),
            ],
        ),
    ]
